/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_codeverification_interpretator_NativeCaller */

#ifndef _Included_com_codeverification_interpretator_NativeCaller
#define _Included_com_codeverification_interpretator_NativeCaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_codeverification_interpretator_NativeCaller
 * Method:    callNativeFunc
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Lcom/codeverification/interpretator/AbstractValue;[Ljava/lang/String;Ljava/lang/String;)Lcom/codeverification/interpretator/AbstractValue;
 */
JNIEXPORT jobject JNICALL Java_com_codeverification_interpretator_NativeCaller_callNativeFunc
  (JNIEnv *, jobject, jstring, jstring, jobjectArray, jobjectArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
